type CountryTypeDb = {
  _id: object,
  nameEn: string,
  nameRu: string,
  nameBe: string,
  topLevelDomain: Object,
  articleEn: string,
  articleRu: string,
  articleBe: string,
  videoEn: string,
  videoRu: string,
  videoBe: string,
  photoSrc1: string,
  photoSrc2: string,
  photoSrc3: string,
  alpha2Code: string,
  alpha3Code: string,
  callingCodes: object,
  capital: string,
  altSpellings: object,
  region: string,
  subregion: string,
  population: number,
  latlng: object,
  demonym: string,
  area: number,
  gini: any,
  timezones: object,
  borders: object,
  nativeName: string,
  numericCode: string,
  currencies: object,
  languages: object,
  translations: object,
  flag: string,
  regionalBlocs: object,
  cioc: string
};

export default CountryTypeDb;
